"""
build_derived.py -- Phase E/Step-2 derived-layer builder.

Per authoritative version it writes derived/<id>/<ver>/:
  * structure.json  -- deterministic (rule_based) parse into units + citations.
  * concepts.json   -- neutral concept tags. Where a model tagging exists in
                       concept_tags.py it is used (generation_method: model,
                       review_status: unreviewed); otherwise a keyword first pass
                       (rule_based) is the fallback.
  * derived-metadata.yaml -- provenance list, one record per artifact.

It also writes two corpus-level derived products:
  * derived/concept-index.json and docs/concept-index.md -- every provision that
    addresses each neutral concept, across all instruments (the cross-instrument view).
  * docs/concept-vocabulary.md -- the concept vocabulary with definitions.

All derived, unofficial, traceable to the authoritative text hash. See docs/design/06.
"""
import json, os, re, sys
import yaml
sys.path.insert(0, os.path.dirname(__file__))
from hashing import sha256_bytes, normalize_text_bytes  # noqa
import concept_tags

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUTH = os.path.join(REPO, "authoritative")
DER = os.path.join(REPO, "derived")
DOCS = os.path.join(REPO, "docs")
DISCLAIMER = ("Derived, unofficial content generated by the Space Law Corpus. NOT the "
              "authoritative legal text. See the linked authoritative source and its "
              "authentic-language text for anything legally operative.")
VOCAB = concept_tags.VOCAB
MODEL_TAGS = concept_tags.TAGS

# keyword fallback (only used for any instrument without model tags)
KW = {
  "registration": ["registr", "registry"], "liability_and_damage": ["liabilit", "damage caused", "compensation"],
  "jurisdiction_and_control": ["jurisdiction and control"], "non_appropriation": ["national appropriation", "claim of sovereignty"],
  "rescue_and_return": ["rescue", "astronaut", "distress"], "environmental_protection_and_debris": ["contamination", "debris", "harmful interference"],
}
hdr_re = re.compile(r"^(Article|Principle|Guideline)\s+([IVXLCDM]+|[A-D]\.\d+|\d+)\b")
num_re = re.compile(r"^(\d+)\.\s")

def split_units(body):
    paras = [p.strip() for p in body.split("\n\n") if p.strip()]
    n_hdr = sum(1 for p in paras if hdr_re.match(p)); n_num = sum(1 for p in paras if num_re.match(p))
    if n_hdr >= 2: mode, starter = "header", hdr_re
    elif n_num >= 2: mode, starter = "numbered", num_re
    else: return "document", [{"number": None, "label": "(whole text)", "text": "\n\n".join(paras)}]
    units, cur, pre = [], None, []
    for p in paras:
        m = starter.match(p)
        if m:
            if cur: units.append(cur)
            label = p.split("\n")[0].strip() if mode == "header" else "Paragraph " + m.group(1)
            cur = {"number": m.group(m.lastindex), "label": label, "text": p}
        elif cur: cur["text"] += "\n\n" + p
        else: pre.append(p)
    if cur: units.append(cur)
    if pre: units.insert(0, {"number": None, "label": "preamble/chapeau", "text": "\n\n".join(pre)})
    utype = "guideline" if mode == "header" and "Guideline" in paras[0][:12] + (units[1]["label"] if len(units) > 1 else "") \
        else ("article" if mode == "header" and "Article" in (units[1]["label"] if len(units) > 1 else "") else
              ("principle" if mode == "header" else "paragraph"))
    return utype, units

def detect_citations(body):
    pats = [r"resolution\s+\d+\s*\([A-Z]+\)", r"resolution\s+\d+/\d+", r"Charter of the United Nations", r"Outer Space Treaty"]
    return sorted({m for pat in pats for m in re.findall(pat, body)})

def keyword_tags(units):
    tags, doc = [], set()
    for u in units:
        low = u["text"].lower(); hits = [c for c, kws in KW.items() if any(k in low for k in kws)]
        if hits: tags.append({"unit": u["label"], "concepts": hits}); doc.update(hits)
    return tags, sorted(doc)

index = {c: [] for c in VOCAB}
records = []
for root, _, files in os.walk(AUTH):
    if "metadata.yaml" not in files: continue
    meta = yaml.safe_load(open(os.path.join(root, "metadata.yaml"), encoding="utf-8"))
    tpath = os.path.join(root, "text.txt")
    if not os.path.exists(tpath): continue
    full = open(tpath, encoding="utf-8").read()
    body = full.split("\n\n", 1)[1] if "\n\n" in full else full
    cid, ver, sh = meta["corpus_id"], str(meta["version_id"]), meta.get("short_title", meta["corpus_id"])
    src_hash = meta["text_sha256"]
    utype, units = split_units(body)

    if cid in MODEL_TAGS:
        rev = getattr(concept_tags, "REVIEW", {}).get(cid, {})
        tags = [{"unit": u, "concepts": cs, "review_status": rev.get(u, "model_consensus")}
                for u, cs in MODEL_TAGS[cid]]
        doc_concepts = sorted({c for _, cs in MODEL_TAGS[cid] for c in cs})
        method, gen, cnote = ("dual_pass_model_consensus_plus_human_adjudication",
                              "two independent model passes + maintainer adjudication (see reviews/)",
                              "Dual-pass tagging: divergences between two independent model passes were "
                              "adjudicated by the maintainer (reviews/concept-decisions-2026-07.yaml); "
                              "per-unit status in each tag entry.")
    else:
        tags, doc_concepts = keyword_tags(units)
        method, gen, cnote = "rule_based", "build_derived.py v0.2 (keyword fallback)", "Keyword fallback; expect false pos/neg."

    for t in tags:
        for c in t["concepts"]:
            index.setdefault(c, []).append({"corpus_id": cid, "short_title": sh, "version_id": ver, "unit": t["unit"]})

    outdir = os.path.join(DER, cid, ver); os.makedirs(outdir, exist_ok=True)
    json.dump({"_derived": True, "_disclaimer": DISCLAIMER, "corpus_id": cid, "version_id": ver,
               "title": meta["title"], "document_type": meta["document_type"], "adoption_date": meta.get("adoption_date"),
               "unit_type": utype, "unit_count": len(units), "units": units, "citations_detected": detect_citations(body)},
              open(os.path.join(outdir, "structure.json"), "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    json.dump({"_derived": True, "_disclaimer": DISCLAIMER, "corpus_id": cid, "version_id": ver,
               "concept_vocabulary": list(VOCAB), "tagging_method": method,
               "document_concepts": doc_concepts, "tags": tags},
              open(os.path.join(outdir, "concepts.json"), "w", encoding="utf-8"), indent=2, ensure_ascii=False)
    dmeta = [
      {"derived_id": f"{cid}/{ver}/structure", "derived_type": "structure_extraction", "artifact_file": "structure.json",
       "source_corpus_id": cid, "source_version_id": ver, "source_text_sha256": src_hash,
       "generation_method": "rule_based", "generator": "build_derived.py v0.2 (structure)", "generation_date": "2026-07-03",
       "review_status": "unreviewed", "reviewed_by": None, "license": "CC-BY-4.0",
       "confidence_note": f"Deterministic parse into {len(units)} {utype} unit(s).", "disclaimer": DISCLAIMER},
      {"derived_id": f"{cid}/{ver}/concepts", "derived_type": "concept_tags", "artifact_file": "concepts.json",
       "source_corpus_id": cid, "source_version_id": ver, "source_text_sha256": src_hash,
       "generation_method": "hybrid" if cid in MODEL_TAGS else method, "generator": gen,
       "generation_date": "2026-07-04" if cid in MODEL_TAGS else "2026-07-03",
       "review_status": "human_reviewed" if cid in MODEL_TAGS else "unreviewed",
       "reviewed_by": "maintainer (dual-pass adjudication, 2026-07-04)" if cid in MODEL_TAGS else None,
       "license": "CC-BY-4.0",
       "confidence_note": cnote, "disclaimer": DISCLAIMER},
    ]
    tdir = os.path.join(outdir, "translations")
    if os.path.isdir(tdir):
        for tf in sorted(os.listdir(tdir)):
            if tf.endswith(".md"):
                lang = tf[:-3]
                dmeta.append({"derived_id": f"{cid}/{ver}/translation-{lang}", "derived_type": "translation",
                    "artifact_file": f"translations/{tf}", "source_corpus_id": cid, "source_version_id": ver,
                    "source_text_sha256": src_hash, "generation_method": "model", "generator": "claude-opus-4-8",
                    "generation_date": "2026-07-03", "review_status": "unreviewed", "reviewed_by": None,
                    "license": "CC-BY-4.0",
                    "confidence_note": f"Unofficial machine-draft {lang} translation; not legally operative.",
                    "disclaimer": DISCLAIMER})
    yaml.safe_dump(dmeta, open(os.path.join(outdir, "derived-metadata.yaml"), "w", encoding="utf-8"),
                   sort_keys=False, allow_unicode=True)
    records.append((cid, ver, utype, len(units), len(doc_concepts)))

# ---- corpus-level: concept index (json + md) ----
os.makedirs(DER, exist_ok=True)
json.dump({"_derived": True, "_disclaimer": DISCLAIMER, "vocabulary": VOCAB, "index": index},
          open(os.path.join(DER, "concept-index.json"), "w", encoding="utf-8"), indent=2, ensure_ascii=False)

md = ["# Concept Index (derived, unofficial)", "",
      f"_{DISCLAIMER}_", "",
      "For each neutral legal concept, the provisions across the corpus that address it. "
      "Tags were produced by two independent model passes with maintainer adjudication of all divergences (dual-pass review). Concepts describe what a provision is *about*; "
      "they take no position on any doctrine.", ""]
for c in VOCAB:
    entries = index.get(c, [])
    md.append(f"## {c}")
    md.append(f"*{VOCAB[c]}*")
    md.append("")
    if not entries:
        md.append("_(no provisions tagged)_\n"); continue
    by_inst = {}
    for e in entries: by_inst.setdefault((e["short_title"], e["corpus_id"]), []).append(e["unit"])
    for (sh, cid), us in by_inst.items():
        md.append(f"- **{sh}** (`{cid}`): " + "; ".join(us))
    md.append("")
open(os.path.join(DER, "concept-index.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")

# ---- docs: concept vocabulary ----
vmd = ["# Concept Vocabulary", "",
       "The neutral legal concepts used to tag provisions in the derived layer. Each describes what a "
       "provision is *about*; the vocabulary is doctrine-agnostic. Tagging is derived, unofficial, and "
       "traceable to each authoritative text (see `docs/design/06-two-layer-separation.md`).", ""]
for c, d in VOCAB.items():
    vmd.append(f"- **`{c}`** — {d}")
open(os.path.join(DOCS, "concept-vocabulary.md"), "w", encoding="utf-8").write("\n".join(vmd) + "\n")

print(f"Rebuilt derived for {len(records)} instruments.")
print("concept coverage (provisions per concept):")
for c in VOCAB:
    print(f"  {c:42s} {len(index.get(c, [])):2d}")
