"""
build_derived.py -- Phase E derived-layer builder.

For each authoritative document version it produces, in derived/<id>/<ver>/:
  * structure.json  -- deterministic parse into units (articles/principles/
                       paragraphs), dates, and detected citations.
  * concepts.json   -- keyword-based first-pass tagging against the neutral
                       concept vocabulary.
  * derived-metadata.yaml -- a LIST of provenance records (one per artifact),
                       each tracing back to the authoritative text hash.

All output is DERIVED, unofficial, and review_status=unreviewed. These are
deterministic (rule_based) mechanical passes meant to be refined by human/model
review later. Nothing here is authoritative. See docs/design/06.
"""
import json, os, re, sys
import yaml
sys.path.insert(0, os.path.dirname(__file__))
from hashing import sha256_bytes, normalize_text_bytes

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUTH = os.path.join(REPO, "authoritative")
DER = os.path.join(REPO, "derived")
DISCLAIMER = ("Derived, unofficial content generated by the Space Law Corpus. NOT the "
              "authoritative legal text. See the linked authoritative source and its "
              "authentic-language text for anything legally operative.")

CONCEPTS = {
  "registration": ["registr", "state of registry", "registry"],
  "liability": ["liabilit", "liable", "damage caused", "compensation"],
  "jurisdiction_and_control": ["jurisdiction and control", "retain jurisdiction", "jurisdiction over"],
  "non_appropriation": ["national appropriation", "appropriation by claim", "claim of sovereignty", "province of all mankind", "common heritage"],
  "resource_rights": ["natural resources", "exploitation of the natural", "resources of the moon", "utilization of"],
  "abandonment_and_salvage": ["found beyond the territorial", "return of objects", "recover the object", "returned to representatives", "return of the object", "component parts"],
  "state_responsibility": ["international responsibility", "responsibility for national", "authorization and continuing supervision", "non-governmental entities"],
  "rescue_and_return": ["rescue", "astronaut", "distress", "emergency landing", "safely and promptly returned", "envoys of mankind"],
  "environmental_and_debris": ["harmful contamination", "contamination", "adverse changes in the environment", "harmful interference", "debris"],
  "dispute_settlement": ["dispute", "consultation", "peaceful settlement", "arbitration", "negotiation"],
}

hdr_re = re.compile(r"^(Article|Principle)\s+([IVXLCDM]+|\d+)\b")
num_re = re.compile(r"^(\d+)\.\s")

def split_units(body):
    paras = [p.strip() for p in body.split("\n\n") if p.strip()]
    n_hdr = sum(1 for p in paras if hdr_re.match(p))
    n_num = sum(1 for p in paras if num_re.match(p))
    if n_hdr >= 2:
        mode, starter = "header", hdr_re
    elif n_num >= 2:
        mode, starter = "numbered", num_re
    else:
        return "document", [{"number": None, "label": "(whole text)", "text": "\n\n".join(paras)}]
    units, cur, pre = [], None, []
    for p in paras:
        m = starter.match(p)
        if m:
            if cur:
                units.append(cur)
            if mode == "header":
                num, label = m.group(2), p.split("\n")[0].strip()
            else:
                num, label = m.group(1), "Paragraph " + m.group(1)
            cur = {"number": num, "label": label, "text": p}
        else:
            if cur:
                cur["text"] += "\n\n" + p
            else:
                pre.append(p)
    if cur:
        units.append(cur)
    if pre:
        units.insert(0, {"number": None, "label": "preamble/chapeau", "text": "\n\n".join(pre)})
    return ("article" if mode == "header" and "Article" in paras[0][:10] + (units[1]["label"] if len(units) > 1 else "") else
            ("principle" if mode == "header" else "paragraph")), units

def detect_citations(body):
    pats = [r"resolution\s+\d+\s*\([A-Z]+\)", r"resolution\s+\d+/\d+",
            r"Charter of the United Nations", r"Outer Space Treaty",
            r"Treaty on Principles Governing"]
    found = []
    for pat in pats:
        found += re.findall(pat, body)
    return sorted(set(found))

def tag_concepts(units):
    tags, doc = [], set()
    for u in units:
        low = u["text"].lower()
        hits, terms = [], []
        for concept, kws in CONCEPTS.items():
            matched = [k for k in kws if k in low]
            if matched:
                hits.append(concept)
                terms += matched
                doc.add(concept)
        if hits:
            tags.append({"unit": u["label"], "number": u["number"],
                         "concepts": hits, "matched_terms": sorted(set(terms))})
    return tags, sorted(doc)

records = []
for root, _, files in os.walk(AUTH):
    if "metadata.yaml" not in files:
        continue
    meta = yaml.safe_load(open(os.path.join(root, "metadata.yaml"), encoding="utf-8"))
    tpath = os.path.join(root, "text.txt")
    if not os.path.exists(tpath):
        continue
    full = open(tpath, encoding="utf-8").read()
    body = full.split("\n\n", 1)[1] if "\n\n" in full else full   # drop the title line
    cid, ver = meta["corpus_id"], str(meta["version_id"])
    src_hash = meta["text_sha256"]
    unit_type, units = split_units(body)
    citations = detect_citations(body)
    tags, doc_concepts = tag_concepts(units)

    outdir = os.path.join(DER, cid, ver)
    os.makedirs(outdir, exist_ok=True)
    structure = {
        "_derived": True, "_disclaimer": DISCLAIMER,
        "corpus_id": cid, "version_id": ver, "title": meta["title"],
        "document_type": meta["document_type"],
        "adoption_date": meta.get("adoption_date"),
        "entry_into_force_date": meta.get("entry_into_force_date"),
        "unit_type": unit_type, "unit_count": len(units),
        "units": units, "citations_detected": citations,
    }
    concepts = {
        "_derived": True, "_disclaimer": DISCLAIMER,
        "corpus_id": cid, "version_id": ver,
        "concept_vocabulary": list(CONCEPTS.keys()),
        "method": "keyword-based first pass (rule_based); crude, for human/model review",
        "document_concepts": doc_concepts, "tags": tags,
    }
    json.dump(structure, open(os.path.join(outdir, "structure.json"), "w", encoding="utf-8"),
              indent=2, ensure_ascii=False)
    json.dump(concepts, open(os.path.join(outdir, "concepts.json"), "w", encoding="utf-8"),
              indent=2, ensure_ascii=False)
    dmeta = [
        {"derived_id": f"{cid}/{ver}/structure", "derived_type": "structure_extraction",
         "artifact_file": "structure.json", "source_corpus_id": cid, "source_version_id": ver,
         "source_text_sha256": src_hash, "generation_method": "rule_based",
         "generator": "build_derived.py v0.1 (structure)", "generation_date": "2026-07-02",
         "review_status": "unreviewed", "reviewed_by": None, "license": "CC-BY-4.0",
         "confidence_note": f"Deterministic parse into {len(units)} {unit_type} unit(s).",
         "disclaimer": DISCLAIMER},
        {"derived_id": f"{cid}/{ver}/concepts", "derived_type": "concept_tags",
         "artifact_file": "concepts.json", "source_corpus_id": cid, "source_version_id": ver,
         "source_text_sha256": src_hash, "generation_method": "rule_based",
         "generator": "build_derived.py v0.1 (concepts)", "generation_date": "2026-07-02",
         "review_status": "unreviewed", "reviewed_by": None, "license": "CC-BY-4.0",
         "confidence_note": "Keyword-based first pass; not legally reviewed; expect false pos/neg.",
         "disclaimer": DISCLAIMER},
    ]
    yaml.safe_dump(dmeta, open(os.path.join(outdir, "derived-metadata.yaml"), "w", encoding="utf-8"),
                   sort_keys=False, allow_unicode=True)
    records.append((cid, ver, unit_type, len(units), len(tags), doc_concepts))

for cid, ver, ut, nu, nt, dc in sorted(records):
    print(f"{cid:26s} {ver:12s} units={nu:2d}({ut:9s}) tagged_units={nt:2d} concepts={dc}")
print(f"\nBuilt derived artifacts for {len(records)} documents.")
