#!/usr/bin/env python3
"""
build_anchors.py -- stable, verifiable citation anchors for external systems.

Downstream systems (e.g. an asset registry citing a legal basis) need to point at a SPECIFIC
Part / Principle of an instrument and be able to prove that what they cited has not changed.

This emits derived/anchors.json (+ .md) mapping a stable anchor id to the location of that unit
inside an authoritative text, with:
  * source_text_sha256 -- the hash of the whole authoritative text the anchor lives in
  * span_sha256        -- the hash of the anchored span itself
so a citation can be verified byte-exactly WITHOUT this file restating any of the text.

Design rule (two-layer wall): anchors carry ids, labels, offsets and hashes ONLY. No provision
text, no summaries, no paraphrase. The authoritative text remains the single place the words live.

Anchor id format:  <citation_key>#<fragment>      e.g. 1721(XVI)#part-B , 1962(XVIII)#principle-8
Anchors are also addressable by corpus_id:        un/ga/res-1721-XVI#part-B

Run: python3 scripts/build_anchors.py   (regenerable; safe to re-run)
"""
import json, os, re, sys, glob
import yaml
sys.path.insert(0, os.path.dirname(__file__))
from hashing import sha256_bytes, normalize_text_bytes

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUTH = os.path.join(REPO, "authoritative")
DER  = os.path.join(REPO, "derived")

# Which instruments expose part/principle anchors, and how their units are recognised.
# rule: "letter_part"  -> a bare capital letter on its own line opens a Part (res. 1721 A / B)
#       "numbered"     -> "N. ..." opens a numbered principle/paragraph (res. 1962 principles)
SCHEMES = {
    "un/ga/res-1721-XVI":   {"citation_key": "1721(XVI)",   "rule": "letter_part", "fragment": "part-{}"},
    "un/ga/res-1962-XVIII": {"citation_key": "1962(XVIII)", "rule": "numbered",    "fragment": "principle-{}"},
}

def paras(text):
    out, pos = [], 0
    for p in text.split("\n\n"):
        s = p.strip()
        if s:
            i = text.index(p, pos)
            out.append({"text": p, "start": i, "end": i + len(p)})
            pos = i + len(p)
    return out

def build_for(cid, ver, d, meta, scheme):
    text = open(os.path.join(d, "text.txt"), encoding="utf-8").read()
    ps = paras(text)
    groups, cur = [], None
    for p in ps:
        s = p["text"].strip()
        if scheme["rule"] == "letter_part":
            m = re.fullmatch(r"([A-E])", s)
            if m:
                cur = {"key": m.group(1), "start": p["start"], "end": p["end"]}
                groups.append(cur); continue
        else:
            m = re.match(r"^(\d+)\.\s", s)
            if m:
                cur = {"key": m.group(1), "start": p["start"], "end": p["end"]}
                groups.append(cur); continue
        if cur: cur["end"] = p["end"]
    anchors = []
    for g in groups:
        span = text[g["start"]:g["end"]]
        frag = scheme["fragment"].format(g["key"])
        anchors.append({
            "anchor_id":   f'{scheme["citation_key"]}#{frag}',
            "alt_anchor_id": f"{cid}#{frag}",
            "fragment":    frag,
            "citation_key": scheme["citation_key"],
            "corpus_id":   cid,
            "version_id":  ver,
            "label":       ("Part " if scheme["rule"] == "letter_part" else "Principle ") + g["key"],
            "char_start":  g["start"], "char_end": g["end"], "char_len": len(span),
            "span_sha256": sha256_bytes(normalize_text_bytes(span)),
            "source_text_sha256": meta["text_sha256"],
            "site_url":    f"i_{cid.replace('/','_')}.html#{frag}",
        })
    return anchors

def main():
    all_anchors, index = [], {}
    for mp in sorted(glob.glob(os.path.join(AUTH, "**", "metadata.yaml"), recursive=True)):
        meta = yaml.safe_load(open(mp, encoding="utf-8"))
        cid = meta["corpus_id"]
        if cid not in SCHEMES: continue
        if meta.get("authoritative_status") == "authoritative_missing": continue
        a = build_for(cid, str(meta["version_id"]), os.path.dirname(mp), meta, SCHEMES[cid])
        all_anchors += a
    for a in all_anchors:
        index[a["anchor_id"]] = a["alt_anchor_id"]
    doc = {"_derived": True,
           "_disclaimer": ("Derived, unofficial locator index generated by the corpus toolkit. It contains "
                           "identifiers, offsets and hashes ONLY - never the text of a provision. Resolve an "
                           "anchor against the authoritative text named in corpus_id/version_id."),
           "_note": ("span_sha256 lets a citing system verify that the anchored span is byte-for-byte what it "
                     "cited, without this file reproducing it. If an authoritative text is ever corrected, the "
                     "span hash changes and stale citations are detectable."),
           "generated_from": "authoritative/", "anchor_count": len(all_anchors), "anchors": all_anchors}
    os.makedirs(DER, exist_ok=True)
    json.dump(doc, open(os.path.join(DER, "anchors.json"), "w", encoding="utf-8"),
              indent=2, ensure_ascii=False)
    md = ["# Citation anchors (derived, unofficial)", "",
          "_Identifiers, offsets and hashes only - no provision text. Resolve against the authoritative record._", "",
          "| Anchor | Instrument | Unit | Span SHA-256 (short) |", "|---|---|---|---|"]
    for a in all_anchors:
        md.append(f'| `{a["anchor_id"]}` | `{a["corpus_id"]}` @ {a["version_id"]} | {a["label"]} | `{a["span_sha256"][7:23]}…` |')
    open(os.path.join(DER, "anchors.md"), "w", encoding="utf-8").write("\n".join(md) + "\n")
    print(f"anchors: {len(all_anchors)}")
    for a in all_anchors: print(f'  {a["anchor_id"]:26s} {a["label"]:14s} {a["char_len"]:5d} chars  {a["site_url"]}')

if __name__ == "__main__":
    main()
