"""
concept_tags.py -- neutral concept vocabulary and the reviewed concept tagging.

Tags are DERIVED, unofficial content produced by the DUAL-PASS method (2026-07-04):
two independent model tagging passes (reviews/concept-passes/pass-A.json, pass-B.json)
were diffed (scripts/diff_passes.py); every divergence was adjudicated by the
maintainer (reviews/concept-decisions-2026-07.yaml). Each unit carries a status in
REVIEW: "model_consensus" (both passes agreed) or "human_adjudicated" (maintainer
ruling). Procedural final clauses, preambles, scope exclusions and pure definitions
are intentionally untagged.

Neutrality note: the vocabulary describes what a provision is ABOUT; it takes no
position on any doctrine. 'abandonment_and_salvage' is one lens among many.
"""

VOCAB = {
 "freedom_of_exploration_and_use": "Freedom to explore and use outer space by all States; province/benefit of all; freedom of scientific investigation.",
 "non_appropriation": "Outer space and celestial bodies not subject to national appropriation by sovereignty, use, occupation or other means.",
 "peaceful_use_and_non_militarization": "Peaceful purposes; prohibition of WMD/weapons; no military bases; no intentional harmful acts.",
 "state_responsibility_and_supervision": "International responsibility of States for national activities, including authorization and continuing supervision of non-governmental entities.",
 "jurisdiction_and_control": "Retention of jurisdiction and control over space objects and personnel; ownership of objects.",
 "registration": "Registration of space objects in national and UN registries; furnishing of identifying information.",
 "liability_and_damage": "Responsibility/liability for damage caused by space objects; compensation; claims procedures.",
 "rescue_and_return": "Rescue and return of astronauts/personnel in distress; assistance.",
 "abandonment_and_salvage": "Ownership, recovery and return of space objects (and parts) found beyond the launching State's limits.",
 "resource_rights": "Rights over natural resources of celestial bodies; exploitation; common-heritage regime; samples.",
 "environmental_protection_and_debris": "Protection of the space and Earth environment; harmful contamination; space debris mitigation; long-term sustainability.",
 "international_cooperation_and_transparency": "International cooperation; information-sharing; notification; consultation; benefit-sharing; capacity-building; openness.",
 "dispute_settlement_and_consultation": "Consultation and settlement of disputes; claims commissions; arbitration.",
 "safety_of_space_operations": "Safety of operations; conjunction assessment; collision avoidance; re-entry safety; nuclear-power-source and operational safety.",
}

DUAL_PASS = {
 "method": "dual_pass_model_consensus_plus_human_adjudication",
 "pass_files": "reviews/concept-passes/",
 "diff_tool": "scripts/diff_passes.py",
 "decisions": "reviews/concept-decisions-2026-07.yaml",
 "adjudicated": "2026-07-04",
 "inter_pass_agreement": "118/208 units (56.7%); 69 divergences adjudicated",
}

# corpus_id -> list of [unit_label, [concepts]]
TAGS = {
 "un/treaty/ost-1967": [
  ["Article I", ["freedom_of_exploration_and_use", "international_cooperation_and_transparency"]],
  ["Article II", ["non_appropriation"]],
  ["Article III", ["international_cooperation_and_transparency", "peaceful_use_and_non_militarization"]],
  ["Article IV", ["peaceful_use_and_non_militarization"]],
  ["Article V", ["international_cooperation_and_transparency", "rescue_and_return"]],
  ["Article VI", ["state_responsibility_and_supervision"]],
  ["Article VII", ["liability_and_damage"]],
  ["Article VIII", ["abandonment_and_salvage", "jurisdiction_and_control"]],
  ["Article IX", ["dispute_settlement_and_consultation", "environmental_protection_and_debris", "international_cooperation_and_transparency"]],
  ["Article X", ["international_cooperation_and_transparency"]],
  ["Article XI", ["international_cooperation_and_transparency"]],
  ["Article XII", ["international_cooperation_and_transparency"]],
  ["Article XIII", ["international_cooperation_and_transparency", "state_responsibility_and_supervision"]],
 ],
 "un/treaty/rescue-1968": [
  ["Article 1", ["international_cooperation_and_transparency", "rescue_and_return"]],
  ["Article 2", ["international_cooperation_and_transparency", "rescue_and_return"]],
  ["Article 3", ["rescue_and_return"]],
  ["Article 4", ["rescue_and_return"]],
  ["Article 5", ["abandonment_and_salvage", "international_cooperation_and_transparency", "liability_and_damage", "safety_of_space_operations"]],
 ],
 "un/treaty/liability-1972": [
  ["Article I", ["liability_and_damage"]],
  ["Article II", ["liability_and_damage"]],
  ["Article III", ["liability_and_damage"]],
  ["Article IV", ["liability_and_damage"]],
  ["Article V", ["liability_and_damage"]],
  ["Article VI", ["liability_and_damage"]],
  ["Article VII", ["liability_and_damage"]],
  ["Article VIII", ["liability_and_damage"]],
  ["Article IX", ["liability_and_damage"]],
  ["Article X", ["liability_and_damage"]],
  ["Article XI", ["dispute_settlement_and_consultation", "liability_and_damage"]],
  ["Article XII", ["liability_and_damage"]],
  ["Article XIII", ["liability_and_damage"]],
  ["Article XIV", ["dispute_settlement_and_consultation", "liability_and_damage"]],
  ["Article XV", ["dispute_settlement_and_consultation"]],
  ["Article XVI", ["dispute_settlement_and_consultation"]],
  ["Article XVII", ["dispute_settlement_and_consultation"]],
  ["Article XVIII", ["dispute_settlement_and_consultation", "liability_and_damage"]],
  ["Article XIX", ["dispute_settlement_and_consultation"]],
  ["Article XX", ["dispute_settlement_and_consultation"]],
  ["Article XXI", ["international_cooperation_and_transparency"]],
  ["Article XXII", ["liability_and_damage", "state_responsibility_and_supervision"]],
 ],
 "un/treaty/registration-1975": [
  ["Article I", ["registration"]],
  ["Article II", ["registration"]],
  ["Article III", ["international_cooperation_and_transparency", "registration"]],
  ["Article IV", ["international_cooperation_and_transparency", "registration"]],
  ["Article V", ["registration"]],
  ["Article VI", ["international_cooperation_and_transparency", "liability_and_damage", "registration"]],
  ["Article VII", ["registration", "state_responsibility_and_supervision"]],
 ],
 "un/treaty/moon-1979": [
  ["Article 2", ["peaceful_use_and_non_militarization"]],
  ["Article 3", ["peaceful_use_and_non_militarization"]],
  ["Article 4", ["freedom_of_exploration_and_use", "international_cooperation_and_transparency"]],
  ["Article 5", ["international_cooperation_and_transparency"]],
  ["Article 6", ["freedom_of_exploration_and_use", "resource_rights"]],
  ["Article 7", ["environmental_protection_and_debris"]],
  ["Article 8", ["freedom_of_exploration_and_use"]],
  ["Article 9", ["freedom_of_exploration_and_use", "international_cooperation_and_transparency"]],
  ["Article 10", ["rescue_and_return", "safety_of_space_operations"]],
  ["Article 11", ["non_appropriation", "resource_rights"]],
  ["Article 12", ["abandonment_and_salvage", "jurisdiction_and_control"]],
  ["Article 13", ["abandonment_and_salvage", "international_cooperation_and_transparency"]],
  ["Article 14", ["liability_and_damage", "state_responsibility_and_supervision"]],
  ["Article 15", ["dispute_settlement_and_consultation", "international_cooperation_and_transparency"]],
  ["Article 16", ["state_responsibility_and_supervision"]],
 ],
 "un/ga/res-1962-XVIII": [
  ["Paragraph 1", ["freedom_of_exploration_and_use"]],
  ["Paragraph 2", ["freedom_of_exploration_and_use"]],
  ["Paragraph 3", ["non_appropriation"]],
  ["Paragraph 4", ["international_cooperation_and_transparency", "peaceful_use_and_non_militarization"]],
  ["Paragraph 5", ["state_responsibility_and_supervision"]],
  ["Paragraph 6", ["dispute_settlement_and_consultation", "environmental_protection_and_debris", "international_cooperation_and_transparency"]],
  ["Paragraph 7", ["abandonment_and_salvage", "jurisdiction_and_control"]],
  ["Paragraph 8", ["liability_and_damage"]],
  ["Paragraph 9", ["rescue_and_return"]],
 ],
 "un/ga/res-37-92": [
  ["Paragraph 1", ["international_cooperation_and_transparency"]],
  ["Paragraph 2", ["international_cooperation_and_transparency"]],
  ["Paragraph 3", ["international_cooperation_and_transparency", "peaceful_use_and_non_militarization"]],
  ["Paragraph 5", ["freedom_of_exploration_and_use", "state_responsibility_and_supervision"]],
  ["Paragraph 6", ["international_cooperation_and_transparency"]],
  ["Paragraph 7", ["dispute_settlement_and_consultation"]],
  ["Paragraph 8", ["state_responsibility_and_supervision"]],
  ["Paragraph 9", ["state_responsibility_and_supervision"]],
  ["Paragraph 10", ["dispute_settlement_and_consultation", "international_cooperation_and_transparency"]],
  ["Paragraph 11", ["international_cooperation_and_transparency"]],
  ["Paragraph 12", ["international_cooperation_and_transparency"]],
  ["Paragraph 13", ["dispute_settlement_and_consultation", "international_cooperation_and_transparency"]],
  ["Paragraph 14", ["international_cooperation_and_transparency"]],
 ],
 "un/ga/res-41-65": [
  ["Principle II", ["freedom_of_exploration_and_use"]],
  ["Principle IV", ["freedom_of_exploration_and_use"]],
  ["Principle V", ["international_cooperation_and_transparency"]],
  ["Principle VI", ["international_cooperation_and_transparency"]],
  ["Principle VII", ["international_cooperation_and_transparency"]],
  ["Principle VIII", ["international_cooperation_and_transparency"]],
  ["Principle IX", ["international_cooperation_and_transparency", "registration"]],
  ["Principle X", ["environmental_protection_and_debris", "international_cooperation_and_transparency"]],
  ["Principle XI", ["international_cooperation_and_transparency"]],
  ["Principle XII", ["international_cooperation_and_transparency"]],
  ["Principle XIII", ["dispute_settlement_and_consultation", "international_cooperation_and_transparency"]],
  ["Principle XIV", ["state_responsibility_and_supervision"]],
  ["Principle XV", ["dispute_settlement_and_consultation"]],
 ],
 "un/ga/res-47-68": [
  ["Principle 3", ["environmental_protection_and_debris", "safety_of_space_operations"]],
  ["Principle 4", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Principle 5", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Principle 6", ["dispute_settlement_and_consultation", "international_cooperation_and_transparency"]],
  ["Principle 7", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Principle 8", ["state_responsibility_and_supervision"]],
  ["Principle 9", ["liability_and_damage"]],
  ["Principle 10", ["dispute_settlement_and_consultation"]],
 ],
 "un/ga/res-51-122": [
  ["Paragraph 1", ["freedom_of_exploration_and_use", "international_cooperation_and_transparency"]],
  ["Paragraph 2", ["international_cooperation_and_transparency"]],
  ["Paragraph 3", ["international_cooperation_and_transparency"]],
  ["Paragraph 4", ["international_cooperation_and_transparency"]],
  ["Paragraph 5", ["international_cooperation_and_transparency"]],
  ["Paragraph 6", ["international_cooperation_and_transparency"]],
  ["Paragraph 7", ["international_cooperation_and_transparency"]],
  ["Paragraph 8", ["international_cooperation_and_transparency"]],
 ],
 "un/softlaw/copuos-debris-mitigation-2007": [
  ["Guideline 1", ["environmental_protection_and_debris"]],
  ["Guideline 2", ["environmental_protection_and_debris", "safety_of_space_operations"]],
  ["Guideline 3", ["environmental_protection_and_debris", "safety_of_space_operations"]],
  ["Guideline 4", ["environmental_protection_and_debris", "safety_of_space_operations"]],
  ["Guideline 5", ["environmental_protection_and_debris", "safety_of_space_operations"]],
  ["Guideline 6", ["environmental_protection_and_debris"]],
  ["Guideline 7", ["environmental_protection_and_debris"]],
 ],
 "un/softlaw/lts-guidelines-2019": [
  ["Guideline A.1", ["state_responsibility_and_supervision"]],
  ["Guideline A.2", ["state_responsibility_and_supervision"]],
  ["Guideline A.3", ["state_responsibility_and_supervision"]],
  ["Guideline A.4", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Guideline A.5", ["registration"]],
  ["Guideline B.1", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Guideline B.2", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Guideline B.3", ["environmental_protection_and_debris", "international_cooperation_and_transparency"]],
  ["Guideline B.4", ["safety_of_space_operations"]],
  ["Guideline B.5", ["safety_of_space_operations"]],
  ["Guideline B.6", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Guideline B.7", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Guideline B.8", ["safety_of_space_operations"]],
  ["Guideline B.9", ["international_cooperation_and_transparency", "safety_of_space_operations"]],
  ["Guideline B.10", ["safety_of_space_operations"]],
  ["Guideline C.1", ["international_cooperation_and_transparency"]],
  ["Guideline C.2", ["international_cooperation_and_transparency"]],
  ["Guideline C.3", ["international_cooperation_and_transparency"]],
  ["Guideline C.4", ["international_cooperation_and_transparency"]],
  ["Guideline D.1", ["environmental_protection_and_debris", "international_cooperation_and_transparency"]],
  ["Guideline D.2", ["environmental_protection_and_debris"]],
 ],
 "nat/usa/space-resources-2015": [
  ["§51301 Definitions", ["resource_rights"]],
  ["§51302 Commercial exploration and commercial recovery", ["freedom_of_exploration_and_use", "resource_rights", "state_responsibility_and_supervision"]],
  ["§51303 Asteroid resource and space resource rights", ["resource_rights"]],
 ],
 "nat/lux/ressources-espace-2017": [
  ["Art. 1er", ["non_appropriation", "resource_rights"]],
  ["Art. 2", ["state_responsibility_and_supervision"]],
  ["Art. 3", ["resource_rights", "state_responsibility_and_supervision"]],
  ["Art. 4", ["state_responsibility_and_supervision"]],
  ["Art. 5", ["state_responsibility_and_supervision"]],
  ["Art. 6", ["state_responsibility_and_supervision"]],
  ["Art. 7", ["state_responsibility_and_supervision"]],
  ["Art. 8", ["state_responsibility_and_supervision"]],
  ["Art. 9", ["state_responsibility_and_supervision"]],
  ["Art. 10", ["liability_and_damage", "state_responsibility_and_supervision"]],
  ["Art. 11", ["state_responsibility_and_supervision"]],
  ["Art. 12", ["state_responsibility_and_supervision"]],
  ["Art. 14", ["state_responsibility_and_supervision"]],
  ["Art. 15", ["state_responsibility_and_supervision"]],
  ["Art. 16", ["liability_and_damage"]],
  ["Art. 18", ["state_responsibility_and_supervision"]],
 ],
 "nat/fra/loi-operations-spatiales-2008": [
  ["Art. 1", ["liability_and_damage"]],
  ["Art. 2", ["state_responsibility_and_supervision"]],
  ["Art. 3", ["jurisdiction_and_control", "state_responsibility_and_supervision"]],
  ["Art. 4", ["safety_of_space_operations", "state_responsibility_and_supervision"]],
  ["Art. 5", ["environmental_protection_and_debris", "safety_of_space_operations"]],
  ["Art. 6", ["liability_and_damage", "state_responsibility_and_supervision"]],
  ["Art. 7", ["state_responsibility_and_supervision"]],
  ["Art. 7-1", ["state_responsibility_and_supervision"]],
  ["Art. 8", ["safety_of_space_operations", "state_responsibility_and_supervision"]],
  ["Art. 9", ["state_responsibility_and_supervision"]],
  ["Art. 10", ["state_responsibility_and_supervision"]],
  ["Art. 11", ["state_responsibility_and_supervision"]],
  ["Art. 11-2", ["jurisdiction_and_control", "state_responsibility_and_supervision"]],
  ["Art. 12", ["registration"]],
  ["Art. 13", ["liability_and_damage"]],
  ["Art. 13-1", ["liability_and_damage"]],
  ["Art. 14", ["liability_and_damage"]],
  ["Art. 15", ["liability_and_damage"]],
  ["Art. 16", ["liability_and_damage"]],
  ["Art. 17", ["liability_and_damage"]],
  ["Art. 18", ["liability_and_damage"]],
  ["Art. 19", ["liability_and_damage"]],
  ["Art. 20", ["liability_and_damage"]],
  ["Art. 23", ["state_responsibility_and_supervision"]],
  ["Art. 24", ["state_responsibility_and_supervision"]],
  ["Art. 25", ["state_responsibility_and_supervision"]],
 ],
}

# corpus_id -> unit_label -> review status
REVIEW = {
 "un/treaty/ost-1967": {"Article I": "human_adjudicated", "Article II": "model_consensus", "Article III": "model_consensus", "Article IV": "model_consensus", "Article V": "model_consensus", "Article VI": "model_consensus", "Article VII": "model_consensus", "Article VIII": "model_consensus", "Article IX": "model_consensus", "Article X": "model_consensus", "Article XI": "model_consensus", "Article XII": "model_consensus", "Article XIII": "model_consensus"},
 "un/treaty/rescue-1968": {"Article 1": "model_consensus", "Article 2": "human_adjudicated", "Article 3": "model_consensus", "Article 4": "model_consensus", "Article 5": "human_adjudicated"},
 "un/treaty/liability-1972": {"Article I": "model_consensus", "Article II": "model_consensus", "Article III": "model_consensus", "Article IV": "model_consensus", "Article V": "model_consensus", "Article VI": "model_consensus", "Article VII": "model_consensus", "Article VIII": "human_adjudicated", "Article IX": "human_adjudicated", "Article X": "human_adjudicated", "Article XI": "model_consensus", "Article XII": "human_adjudicated", "Article XIII": "human_adjudicated", "Article XIV": "human_adjudicated", "Article XV": "model_consensus", "Article XVI": "human_adjudicated", "Article XVII": "human_adjudicated", "Article XVIII": "model_consensus", "Article XIX": "model_consensus", "Article XX": "human_adjudicated", "Article XXI": "human_adjudicated", "Article XXII": "model_consensus"},
 "un/treaty/registration-1975": {"Article I": "model_consensus", "Article II": "model_consensus", "Article III": "model_consensus", "Article IV": "model_consensus", "Article V": "model_consensus", "Article VI": "human_adjudicated", "Article VII": "model_consensus"},
 "un/treaty/moon-1979": {"Article 2": "model_consensus", "Article 3": "model_consensus", "Article 4": "model_consensus", "Article 5": "model_consensus", "Article 6": "model_consensus", "Article 7": "model_consensus", "Article 8": "model_consensus", "Article 9": "human_adjudicated", "Article 10": "human_adjudicated", "Article 11": "model_consensus", "Article 12": "human_adjudicated", "Article 13": "human_adjudicated", "Article 14": "human_adjudicated", "Article 15": "model_consensus", "Article 16": "model_consensus"},
 "un/ga/res-1962-XVIII": {"Paragraph 1": "human_adjudicated", "Paragraph 2": "model_consensus", "Paragraph 3": "model_consensus", "Paragraph 4": "model_consensus", "Paragraph 5": "model_consensus", "Paragraph 6": "human_adjudicated", "Paragraph 7": "model_consensus", "Paragraph 8": "model_consensus", "Paragraph 9": "model_consensus"},
 "un/ga/res-37-92": {"Paragraph 1": "human_adjudicated", "Paragraph 2": "human_adjudicated", "Paragraph 3": "human_adjudicated", "Paragraph 5": "human_adjudicated", "Paragraph 6": "human_adjudicated", "Paragraph 7": "human_adjudicated", "Paragraph 8": "human_adjudicated", "Paragraph 9": "human_adjudicated", "Paragraph 10": "human_adjudicated", "Paragraph 11": "human_adjudicated", "Paragraph 12": "human_adjudicated", "Paragraph 13": "human_adjudicated", "Paragraph 14": "human_adjudicated"},
 "un/ga/res-41-65": {"Principle II": "human_adjudicated", "Principle IV": "human_adjudicated", "Principle V": "human_adjudicated", "Principle VI": "human_adjudicated", "Principle VII": "human_adjudicated", "Principle VIII": "human_adjudicated", "Principle IX": "human_adjudicated", "Principle X": "human_adjudicated", "Principle XI": "human_adjudicated", "Principle XII": "human_adjudicated", "Principle XIII": "human_adjudicated", "Principle XIV": "model_consensus", "Principle XV": "model_consensus"},
 "un/ga/res-47-68": {"Principle 3": "model_consensus", "Principle 4": "human_adjudicated", "Principle 5": "model_consensus", "Principle 6": "human_adjudicated", "Principle 7": "human_adjudicated", "Principle 8": "model_consensus", "Principle 9": "model_consensus", "Principle 10": "human_adjudicated"},
 "un/ga/res-51-122": {"Paragraph 1": "human_adjudicated", "Paragraph 2": "human_adjudicated", "Paragraph 3": "human_adjudicated", "Paragraph 4": "human_adjudicated", "Paragraph 5": "human_adjudicated", "Paragraph 6": "human_adjudicated", "Paragraph 7": "human_adjudicated", "Paragraph 8": "human_adjudicated"},
 "un/softlaw/copuos-debris-mitigation-2007": {"Guideline 1": "model_consensus", "Guideline 2": "model_consensus", "Guideline 3": "model_consensus", "Guideline 4": "human_adjudicated", "Guideline 5": "human_adjudicated", "Guideline 6": "model_consensus", "Guideline 7": "model_consensus"},
 "un/softlaw/lts-guidelines-2019": {"Guideline A.1": "model_consensus", "Guideline A.2": "model_consensus", "Guideline A.3": "model_consensus", "Guideline A.4": "model_consensus", "Guideline A.5": "model_consensus", "Guideline B.1": "model_consensus", "Guideline B.2": "model_consensus", "Guideline B.3": "model_consensus", "Guideline B.4": "model_consensus", "Guideline B.5": "model_consensus", "Guideline B.6": "human_adjudicated", "Guideline B.7": "human_adjudicated", "Guideline B.8": "human_adjudicated", "Guideline B.9": "human_adjudicated", "Guideline B.10": "model_consensus", "Guideline C.1": "model_consensus", "Guideline C.2": "model_consensus", "Guideline C.3": "model_consensus", "Guideline C.4": "model_consensus", "Guideline D.1": "human_adjudicated", "Guideline D.2": "model_consensus"},
 "nat/usa/space-resources-2015": {"§51301 Definitions": "model_consensus", "§51302 Commercial exploration and commercial recovery": "human_adjudicated", "§51303 Asteroid resource and space resource rights": "model_consensus"},
 "nat/lux/ressources-espace-2017": {"Art. 1er": "model_consensus", "Art. 2": "human_adjudicated", "Art. 3": "model_consensus", "Art. 4": "human_adjudicated", "Art. 5": "human_adjudicated", "Art. 6": "human_adjudicated", "Art. 7": "model_consensus", "Art. 8": "model_consensus", "Art. 9": "model_consensus", "Art. 10": "human_adjudicated", "Art. 11": "human_adjudicated", "Art. 12": "human_adjudicated", "Art. 14": "human_adjudicated", "Art. 15": "model_consensus", "Art. 16": "model_consensus", "Art. 18": "model_consensus"},
 "nat/fra/loi-operations-spatiales-2008": {"Art. 1": "human_adjudicated", "Art. 2": "human_adjudicated", "Art. 3": "model_consensus", "Art. 4": "model_consensus", "Art. 5": "model_consensus", "Art. 6": "human_adjudicated", "Art. 7": "human_adjudicated", "Art. 7-1": "model_consensus", "Art. 8": "model_consensus", "Art. 9": "human_adjudicated", "Art. 10": "model_consensus", "Art. 11": "model_consensus", "Art. 11-2": "model_consensus", "Art. 12": "model_consensus", "Art. 13": "model_consensus", "Art. 13-1": "model_consensus", "Art. 14": "human_adjudicated", "Art. 15": "model_consensus", "Art. 16": "model_consensus", "Art. 17": "model_consensus", "Art. 18": "model_consensus", "Art. 19": "model_consensus", "Art. 20": "model_consensus", "Art. 23": "model_consensus", "Art. 24": "model_consensus", "Art. 25": "model_consensus"},
}
